<a href="https://colab.research.google.com/github/Danielunigwe/dan1/blob/main/BASIC_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
[3>10]

[False]

In [6]:
20-2

18

In [8]:
(4<1)

False

In [10]:
(8/3)

2.6666666666666665

In [11]:
(6+8)

14

In [13]:
(4&9)

0

In [14]:
(10>20)&(20>10)

False

In [15]:
(10>20)|(20>10)

True

In [17]:
i=0
while i <=5:
  print(i)
  i=i+1

0
1
2
3
4
5


In [21]:
i=0
while i <=5:
  print(i)
  i=i+1
print("Loop Ends")

0
1
2
3
4
5
Loop Ends


In [22]:
i=10
while i <=5:
  print(i)
  i=i+1
print("Loop Ends")

Loop Ends


In [23]:
i=10
while i <=5:
  print(i)
  i=i+1
print("Loop Ends")

Loop Ends


In [25]:
list(range(14))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [28]:
for i in range(6):
  print("Hello World")


Hello World
Hello World
Hello World
Hello World
Hello World
Hello World


In [29]:
import numpy as np
from numpy.random import randn

In [ ]:

x=randn()
if x>1:
 result ="great than 1"
print(x)
print (result)

In [34]:
result= None
x = randn()
if x>1:
 result ="great than 1"
print(x)
print (result)

-1.8549202025160787
None


In [35]:
result= None
x = randn()
if x>1:
 result = "great than 1"
else:
 result = "less than 1"
print(x)
print (result)

-0.019939226275214314
less than 1


In [37]:
result= None
x = randn()
if x>1:
 result = "great than 1"
elif x <-1:
 result = "less than -1"
else:
 result = "Between -1 and 1"
print(x)
print (result)

-1.3144486482502828
less than -1


In [40]:
#creating a list
list1= [1,2,4,10, 'abc', "Good Job", True, 20.29]

In [41]:
list1

[1, 2, 4, 10, 'abc', 'Good Job', True, 20.29]

In [42]:
type(list1)

list

In [43]:
list1[-1]

20.29

In [45]:
list1[6]

True

In [46]:
list1[3]

10

In [ ]:
#getting data from list

In [48]:
list1[2:5+1]

[4, 10, 'abc', 'Good Job']

In [49]:
list1[2:5]

[4, 10, 'abc']

In [50]:
list1[::2]

[1, 4, 'abc', True]

In [51]:
list1[::-1]

[20.29, True, 'Good Job', 'abc', 10, 4, 2, 1]

In [56]:
tuple11=(1,2,3,4,5,6)

In [76]:
print(list1)

[1, 2, 4, 10, 'abc', 'Good Job', True, 20.29]


In [62]:
range(30,41)

range(30, 1)

In [63]:
list(range(30,41))

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [64]:
mylist1 = list(range(30,41))

In [65]:
print(mylist1)

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [68]:
len(mylist1)

11

In [69]:
type(mylist1)

list

In [70]:
max(mylist1)

40

In [71]:
min(mylist1)

30

In [66]:
max("processwhirl")

'w'

In [67]:
min("processwhirl")

'c'

In [ ]:
import numpy as np


In [74]:
a=np.array(list1)
print(a)

['1' '2' '4' '10' 'abc' 'Good Job' 'True' '20.29']


In [75]:
a

array(['1', '2', '4', '10', 'abc', 'Good Job', 'True', '20.29'],
      dtype='<U32')

In [78]:
b=np.array([2345, 6789, 9876, 1456, -1234])

In [83]:
b.mean()

5846.4

In [80]:
b

array([12345,  6789,  9876,  1456, -1234])

In [81]:
b[::2]

array([12345,  9876, -1234])

In [82]:
b[1::2]

array([6789, 1456])

In [85]:
c = b[2:4]

In [ ]:
c

In [86]:
c[:]=222

In [87]:
c

array([222, 222])

In [88]:
b

array([12345,  6789,   222,   222, -1234])